import os

css = '''
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,-apple-system,sans-serif;background:#0a0a1a;color:#e2e8f0;line-height:1.5}
.header{background:linear-gradient(135deg,#1a1040,#0f2040);border-bottom:1px solid #1e3a5f;padding:14px 24px;display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;z-index:10}
.header h1{font-size:18px;font-weight:700;background:linear-gradient(90deg,#60a5fa,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.container{max-width:1100px;margin:0 auto;padding:20px 16px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}
.card{background:#111827;border:1px solid #1e293b;border-radius:10px;padding:18px;cursor:pointer;transition:all .2s}
.card:hover{border-color:#3b82f6;box-shadow:0 4px 20px rgba(59,130,246,.1)}
.card-icon{width:40px;height:40px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:18px;margin-bottom:10px}
.card h2{font-size:15px;font-weight:600;margin-bottom:4px;color:#f1f5f9}
.card p{font-size:12px;color:#64748b}
textarea,input[type=text],input[type=number],select{width:100%;background:#0f172a;border:1px solid #1e293b;border-radius:6px;padding:10px 12px;font-size:13px;color:#e2e8f0;font-family:inherit;outline:none}
textarea:focus,input:focus,select:focus{border-color:#3b82f6}
textarea{min-height:80px;resize:vertical}
.btn{display:inline-flex;align-items:center;gap:6px;padding:8px 16px;border-radius:6px;font-size:12px;font-weight:500;cursor:pointer;border:none;transition:all .15s}
.btn-primary{background:linear-gradient(135deg,#3b82f6,#6366f1);color:#fff}
.btn-primary:hover{opacity:.9}
.btn-secondary{background:#1e293b;color:#94a3b8;border:1px solid #334155}
.btn-secondary:hover{background:#334155;color:#e2e8f0}
.result{margin-top:10px;padding:10px 12px;background:#0f172a;border:1px solid #1e293b;border-radius:6px;font-size:12px;color:#94a3b8;max-height:200px;overflow-y:auto;white-space:pre-wrap}
.stat{display:inline-flex;padding:4px 10px;background:#1e293b;border-radius:4px;font-size:11px;margin:4px 4px 0 0}
.tool-page{max-width:700px;margin:0 auto}
.tool-page h2{font-size:20px;margin-bottom:8px}
.back-btn{display:inline-flex;align-items:center;gap:4px;color:#60a5fa;font-size:12px;cursor:pointer;margin-bottom:16px;background:none;border:none}
.back-btn:hover{color:#93c5fd}
.strength-bar{height:6px;border-radius:3px;transition:all .3s;margin-top:8px;background:#1e293b;width:100%}
.tab-nav{display:flex;gap:2px;margin-bottom:12px;background:#1e293b;padding:2px;border-radius:6px}
.tab-nav button{flex:1;padding:6px;font-size:11px;border-radius:5px;border:none;cursor:pointer;background:none;color:#64748b}
.tab-nav button.active{background:#3b82f6;color:#fff}
.hero{text-align:center;padding:40px 0 20px}
.hero h1{font-size:32px;font-weight:800;margin-bottom:8px;background:linear-gradient(135deg,#60a5fa,#a78bfa,#f472b6);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.hero p{color:#64748b;font-size:14px}
.footer{text-align:center;padding:24px;font-size:11px;color:#334155;border-top:1px solid #1e293b;margin-top:40px}
@media(max-width:640px){.grid{grid-template-columns:1fr}.hero h1{font-size:24px}}
'''

html = '''<!DOCTYPE html>
<html lang="en" class="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="description" content="Free AI-powered online tools: text summarizer, grammar checker, readability scorer, word cloud, password checker. All browser-based.">
<meta property="og:title" content="AI Tool Suite - Free Smart Online Tools">
<title>AI Tool Suite</title>
<style>''' + css + '''</style>
</head>
<body>
<div class="header"><div><h1>AI Tool Suite</h1></div><button class="btn btn-secondary" onclick="showHome()">All Tools</button></div>
<div id="app" class="container"></div>
<div class="footer">All processing happens locally. No uploads.</div>
<script>
/* ---- Router ---- */
const TOOLS={home:{title:"AI Tool Suite",render:renderHome},summarizer:{title:"Summarizer",render:renderSummarizer},grammar:{title:"Grammar",render:renderGrammar},keywords:{title:"Keywords",render:renderKeywords},readability:{title:"Readability",render:renderReadability},wordcloud:{title:"Word Cloud",render:renderWordCloud},password:{title:"Password",render:renderPassword},unit:{title:"Converter",render:renderUnit},percentage:{title:"Percentage",render:renderPercentage}};
function showHome(){TOOLS.home.render(document.getElementById("app"))}
function showTool(id){TOOLS[id].render(document.getElementById("app"))}
document.addEventListener("DOMContentLoaded",showHome);

/* ---- Home ---- */
function renderHome(el){el.innerHTML='''+'''<div class="hero"><h1>Free Smart Online Tools</h1><p>AI-powered tools in your browser. No signups, private.</p></div><div class="grid"><div class="card" onclick="showTool(\'summarizer\')"><div class="card-icon" style="background:rgba(59,130,246,.15);color:#60a5fa">T</div><h2>Text Summarizer</h2><p>Extract key sentences from any text</p></div><div class="card" onclick="showTool(\'grammar\')"><div class="card-icon" style="background:rgba(34,197,94,.15);color:#4ade80">Aa</div><h2>Grammar Checker</h2><p>Find common grammar issues</p></div><div class="card" onclick="showTool(\'keywords\')"><div class="card-icon" style="background:rgba(168,85,247,.15);color:#a78bfa">#</div><h2>Keyword Analyzer</h2><p>Word frequency and density</p></div><div class="card" onclick="showTool(\'readability\')"><div class="card-icon" style="background:rgba(236,72,153,.15);color:#f472b6">Aa</div><h2>Readability Scorer</h2><p>Flesch-Kincaid metrics</p></div><div class="card" onclick="showTool(\'wordcloud\')"><div class="card-icon" style="background:rgba(251,191,36,.15);color:#fbbf24">W</div><h2>Word Cloud</h2><p>Visualize word frequency</p></div><div class="card" onclick="showTool(\'password\')"><div class="card-icon" style="background:rgba(239,68,68,.15);color:#ef4444">P</div><h2>Password Checker</h2><p>Strength analysis</p></div><div class="card" onclick="showTool(\'unit\')"><div class="card-icon" style="background:rgba(14,165,233,.15);color:#38bdf8">U</div><h2>Unit Converter</h2><p>Length, weight, temperature</p></div><div class="card" onclick="showTool(\'percentage\')"><div class="card-icon" style="background:rgba(250,204,21,.15);color:#facc15">%</div><h2>Percentage Calc</h2><p>Quick calculations & tips</p></div></div>'''+'''}

/* ---- Summarizer ---- */
function renderSummarizer(el){el.innerHTML='''+'''<div class="tool-page"><button class="back-btn" onclick="showHome()">&#8592; All Tools</button><h2>AI Text Summarizer</h2><p style="font-size:12px;color:#64748b;margin-bottom:10px">Extractive summarization - picks the most important sentences.</p><textarea id="sum-input" placeholder="Paste text here..." rows="8"></textarea><div style="display:flex;gap:8px;align-items:center;margin:10px 0"><span style="font-size:12px;color:#64748b">Length:</span><input type="range" id="sum-ratio" min="1" max="5" value="3" style="accent-color:#3b82f6;flex:1"><span id="sum-label" style="font-size:12px;color:#94a3b8">Medium</span></div><button class="btn btn-primary" onclick="doSummarize()">Summarize</button><div id="sum-result" class="result" style="display:none"></div></div>'''+''';document.getElementById("sum-ratio").oninput=e=>{document.getElementById("sum-label").textContent=["Very Short","Short","Medium","Long","Full"][e.target.value-1]}}
window.doSummarize=()=>{var t=document.getElementById("sum-input").value,r=[.1,.2,.3,.5,.8][document.getElementById("sum-ratio").value-1],e=document.getElementById("sum-result");if(!t.trim()){e.style.display="block";e.innerHTML="Enter text.";return}var s=t.match(/[^.!?]+[.!?]+/g)||[t];if(s.length<=2){e.style.display="block";e.textContent=t;return}var w=t.toLowerCase().match(/\b\w+\b/g)||[],f={};w.forEach(function(x){if(x.length>3)f[x]=(f[x]||0)+1});s.forEach(function(x,i){var sw=x.toLowerCase().match(/\b\w+\b/g)||[];s[i]={text:x.trim(),score:sw.reduce(function(a,b){return a+(f[b]||0)},0)/Math.max(1,sw.length)}});s.sort(function(a,b){return b.score-a.score});var c=Math.max(1,Math.floor(s.length*r)),sel=s.slice(0,c);sel.sort(function(a,b){return t.indexOf(a.text)-t.indexOf(b.text)});e.style.display="block";e.innerHTML="<strong>Summary ("+c+" sentences):</strong><br><br>"+sel.map(function(x){return x.text}).join(" ")+"<br><br><span style=font-size:10px;color:#475569>Original: "+t.split(/[.!?]+/).filter(Boolean).length+" sentences to "+c+" ("+Math.round(r*100)+"%)</span>"}

/* ---- Grammar ---- */
function renderGrammar(el){el.innerHTML='''+'''<div class="tool-page"><button class="back-btn" onclick="showHome()">&#8592; All Tools</button><h2>Grammar Checker</h2><p style="font-size:12px;color:#64748b;margin-bottom:10px">Checks common English grammar patterns.</p><textarea id="gram-input" placeholder="Type text to check..." rows="8"></textarea><button class="btn btn-primary" style="margin-top:10px" onclick="doGrammar()">Check</button><div id="gram-result" class="result" style="display:none"></div></div>'''+'''}
window.doGrammar=()=>{var t=document.getElementById("gram-input").value,e=document.getElementById("gram-result");if(!t.trim()){e.style.display="block";e.innerHTML="Enter text.";return}var c=[{re:/\bi am\b/gi,fix:"I am"},{re:/\bdont\b/gi,fix:"don\'t"},{re:/\bcant\b/gi,fix:"can\'t"},{re:/\bwont\b/gi,fix:"won\'t"},{re:/\b(its)\s+(a|the|my|your|his|her|our|their|very|not|going|been|really)/gi,fix:"it\'s"},{re:/\b(your)\s+(going|welcome|right|wrong|not|very|really)/gi,fix:"you\'re"},{re:/\b(their)\s+(going|coming|not|very|really|been)\b/gi,fix:"they\'re"},{re:/\bwould of\b/gi,fix:"would have"},{re:/\bcould of\b/gi,fix:"could have"},{re:/\bshould of\b/gi,fix:"should have"}],is=[];c.forEach(function(x){var m,re=new RegExp(x.re.source,x.re.flags);while((m=re.exec(t))!==null){is.push({text:m[0],fix:x.fix,idx:m.index});if(!x.re.flags.includes("g"))break}});e.style.display="block";if(is.length===0)e.innerHTML='''+'''<span style="color:#34d399">No issues found!</span>''';else e.innerHTML="<strong>"+is.length+" issue(s):</strong><br><br>"+is.map(function(i){return '<span style="color:#f87171">"'+i.text+'"</span> to <span style="color:#34d399">"'+i.fix+'"</span>'}).join("<br>")}

/* ---- Keywords ---- */
function renderKeywords(el){el.innerHTML='''+'''<div class="tool-page"><button class="back-btn" onclick="showHome()">&#8592; All Tools</button><h2>Keyword Analyzer</h2><p style="font-size:12px;color:#64748b;margin-bottom:10px">Analyze word frequency and density.</p><textarea id="kw-input" placeholder="Paste content..." rows="8"></textarea><button class="btn btn-primary" style="margin-top:10px" onclick="doKeywords()">Analyze</button><div id="kw-result" class="result" style="display:none"></div></div>'''+'''}
window.doKeywords=()=>{var t=document.getElementById("kw-input").value,e=document.getElementById("kw-result");if(!t.trim()){e.style.display="block";e.innerHTML="Enter text.";return}var w=t.toLowerCase().match(/\b[a-z]{3,}\b/g)||[],stop=new Set(["the","and","that","have","for","not","with","you","this","but","his","from","they","she","will","would","there","their","what","out","about","who","get","which","when","make","can","like","time","just","him","know","take","people","into","your","good","some","could","them","see","other","than","then","now","look","only","come","its","over","think","also","back","after","use","two","how","our","work","first","well","way","even","new","want","because","any","these","give","day","most","been","all"]),f={};w.forEach(function(x){if(!stop.has(x))f[x]=(f[x]||0)+1});var s=Object.entries(f).sort(function(a,b){return b[1]-a[1]}).slice(0,30),total=w.filter(function(x){return!stop.has(x)}).length;e.style.display="block";e.innerHTML="<strong>Words: "+w.length+" | Significant: "+total+" | Unique: "+Object.keys(f).length+"</strong><br><br>"+s.map(function(x,i){return '<span class="stat">#'+(i+1)+" "+x[0]+' <span style="color:#60a5fa">'+x[1]+"</span> ("+(x[1]/Math.max(1,total)*100).toFixed(1)+"%)</span>"}).join("")}

/* ---- Readability ---- */
function renderReadability(el){el.innerHTML='''+'''<div class="tool-page"><button class="back-btn" onclick="showHome()">&#8592; All Tools</button><h2>Readability Scorer</h2><p style="font-size:12px;color:#64748b;margin-bottom:10px">Flesch-Kincaid Grade Level & Reading Ease.</p><textarea id="read-input" placeholder="Paste text..." rows="8"></textarea><button class="btn btn-primary" style="margin-top:10px" onclick="doReadability()">Score</button><div id="read-result" class="result" style="display:none"></div></div>'''+'''}
function countSyllables(w){w=w.toLowerCase().replace(/[^a-z]/g,"");if(w.length<=3)return 1;var m=w.match(/[aeiouy]+/g),c=m?m.length:1;if(w.endsWith("e"))c--;if(w.endsWith("le")&&w.length>3&&!/[aeiouy]/.test(w[w.length-3]))c++;return Math.max(1,c)}
window.doReadability=()=>{var t=document.getElementById("read-input").value,e=document.getElementById("read-result");if(!t.trim()){e.style.display="block";e.innerHTML="Enter text.";return}var s=t.split(/[.!?]+/).filter(function(x){return x.trim()}),w=t.match(/\b\w+\b/g)||[],sy=w.reduce(function(a,x){return a+countSyllables(x)},0),ch=t.replace(/\s/g,"").length,fk=206.835-1.015*(w.length/s.length)-84.6*(sy/w.length),ari=4.71*(ch/w.length)+0.5*(w.length/s.length)-21.43,gl=fk<0?18:0.39*(w.length/s.length)+11.8*(sy/w.length)-15.59,ease=fk>90?"Very Easy":fk>80?"Easy":fk>70?"Fairly Easy":fk>60?"Standard":fk>50?"Fairly Difficult":fk>30?"Difficult":"Very Confusing";e.style.display="block";e.innerHTML="<strong>Flesch Reading Ease:</strong> "+fk.toFixed(1)+" ("+ease+")<br><strong>Flesch-Kincaid Grade:</strong> "+(gl<1?"Kindergarten":gl>18?"College+":"Grade "+Math.round(gl))+"<br><strong>ARI:</strong> "+(ari<1?"KG":ari>18?"College+":"Grade "+Math.round(ari))+"<br><br>Words: "+w.length+" | Sentences: "+s.length+" | Syllables: "+sy}

/* ---- Word Cloud ---- */
function renderWordCloud(el){el.innerHTML='''+'''<div class="tool-page"><button class="back-btn" onclick="showHome()">&#8592; All Tools</button><h2>Word Cloud</h2><p style="font-size:12px;color:#64748b;margin-bottom:10px">Visual word frequency display.</p><textarea id="wc-input" placeholder="Paste text..." rows="6"></textarea><button class="btn btn-primary" style="margin-top:10px" onclick="doWordCloud()">Generate</button><div id="wc-result"></div></div>'''+'''}
window.doWordCloud=()=>{var t=document.getElementById("wc-input").value,c=document.getElementById("wc-result");if(!t.trim()){c.innerHTML="";return}var w=t.toLowerCase().match(/\b[a-z]{3,}\b/g)||[],stop=new Set(["the","and","that","have","for","not","with","you","this","but","his","from","they","she","will","would","there","their","what","out","about","who","get","which","when","make","can","like","time","just","him","know","take","people","into","your","good","some","could","them","see","other","than","then","now","look","only","come","its","over","think","also","back","after","use","two","how","our","work","first","well","way","even","new","want","because","any","these","give","day","most","been","all"]),f={};w.forEach(function(x){if(!stop.has(x))f[x]=(f[x]||0)+1});var s=Object.entries(f).sort(function(a,b){return b[1]-a[1]}).slice(0,60);if(!s.length){c.innerHTML="";return}var max=s[0][1],min=s[s.length-1][1],colors=["#60a5fa","#a78bfa","#f472b6","#4ade80","#fbbf24","#38bdf8","#fb923c","#a3e635","#f87171","#c084fc"],h=s.map(function(x,i){var sz=12+((x[1]-min)/Math.max(1,max-min))*32;return '<span style="display:inline-block;padding:2px 6px;font-size:'+Math.round(sz)+'px;color:'+colors[i%10]+';font-weight:500" title="'+x[1]+'x">'+x[0]+'</span>'}).join("");c.innerHTML='''+'''<div style="margin-top:12px;padding:16px;background:#0f172a;border:1px solid #1e293b;border-radius:6px;line-height:1.8;text-align:center">'''+h+'</div>'}

/* ---- Password ---- */
function renderPassword(el){el.innerHTML='''+'''<div class="tool-page"><button class="back-btn" onclick="showHome()">&#8592; All Tools</button><h2>Password Strength</h2><p style="font-size:12px;color:#64748b;margin-bottom:10px">Check strength locally. Nothing is sent anywhere.</p><input type="text" id="pw-input" placeholder="Type a password..." style="font-family:monospace;font-size:16px;letter-spacing:2px" oninput="doPassword()"><div class="strength-bar" id="pw-bar"></div><div id="pw-result" style="margin-top:8px;font-size:12px;color:#64748b"></div></div>'''+'''}
window.doPassword=()=>{var p=document.getElementById("pw-input").value,b=document.getElementById("pw-bar"),r=document.getElementById("pw-result");if(!p){b.style.width="0";r.textContent="";return}var s=0,c=[];p.length>=8?s++:c.push("Too short (8+)");p.length>=12?s++:c.push("");/[A-Z]/.test(p)?s++:c.push("Add uppercase");/[a-z]/.test(p)?s++:c.push("Add lowercase");/[0-9]/.test(p)?s++:c.push("Add numbers");/[^a-zA-Z0-9]/.test(p)?s++:c.push("Add special chars");/(.)\1{2,}/.test(p)?c.push("Repeated chars detected"):s++;var pct=Math.min(100,(s/7)*100);b.style.width=pct+"%";b.style.background=["#ef4444","#f97316","#facc15","#4ade80"][pct>75?3:pct>50?2:pct>25?1:0];r.innerHTML="<strong>Score: "+s+"/7</strong> | "+(pct>75?"Strong":pct>50?"Moderate":pct>25?"Weak":"Very Weak")+"<br>"+c.filter(function(x){return x}).map(function(x){return x.includes("Add")||x.includes("Too")||x.includes("Repeated")?'<span style="color:#f87171">X '+x+"</span>":""}).filter(function(x){return x}).join("<br>")}

/* ---- Unit Converter ---- */
function renderUnit(el){el.innerHTML='''+'''<div class="tool-page"><button class="back-btn" onclick="showHome()">&#8592; All Tools</button><h2>Unit Converter</h2><div style="display:flex;gap:8px;align-items:center;margin:12px 0;flex-wrap:wrap"><input type="number" id="uc-val" value="1" style="width:100px" oninput="doUnit()"><select id="uc-from" onchange="doUnit()"><option value="m">Meters</option><option value="km">Kilometers</option><option value="cm">Centimeters</option><option value="in">Inches</option><option value="ft">Feet</option><option value="mi">Miles</option><option value="kg">Kilograms</option><option value="g">Grams</option><option value="lb">Pounds</option><option value="oz">Ounces</option><option value="c">Celsius</option><option value="f">Fahrenheit</option></select><span>=</span><span id="uc-result" style="font-size:16px;font-weight:700;color:#60a5fa">3.28 ft</span></div></div>'''+''';setTimeout(doUnit,100)}
window.doUnit=()=>{var v=parseFloat(document.getElementById("uc-val").value)||0,f=document.getElementById("uc-from").value,o=document.getElementById("uc-result"),toM={m:1,km:1000,cm:.01,in:.0254,ft:.3048,mi:1609.34},toKg={kg:1,g:.001,lb:.453592,oz:.0283495};if(f in toM){var b=v*toM[f];o.textContent=b.toFixed(2)+" m | "+(b*3.28084).toFixed(2)+" ft | "+(b*39.3701).toFixed(2)+" in"}else if(f in toKg){var k=v*toKg[f];o.textContent=k.toFixed(2)+" kg | "+(k*2.20462).toFixed(2)+" lb"}else if(f==="c")o.textContent=((v*9/5)+32).toFixed(1)+" F";else o.textContent=((v-32)*5/9).toFixed(1)+" C"}

/* ---- Percentage ---- */
function renderPercentage(el){el.innerHTML='''+'''<div class="tool-page"><button class="back-btn" onclick="showHome()">&#8592; All Tools</button><h2>Percentage Calculator</h2><div class="tab-nav"><button class="active" onclick="setPcMode(0)">% of Number</button><button onclick="setPcMode(1)">% Change</button><button onclick="setPcMode(2)">Tip</button></div><div id="pc-content"></div></div>''';window._pcMode=0;renderPcContent()}
window.setPcMode=m=>{window._pcMode=m;document.querySelectorAll(".tab-nav button").forEach(function(b,i){b.className=i===m?"active":""});renderPcContent()}
function renderPcContent(){var c=document.getElementById("pc-content"),m=window._pcMode;if(m===0)c.innerHTML='''+'''<div style="display:flex;gap:8px;align-items:center;margin-top:12px;flex-wrap:wrap"><input type="number" id="pcn-val" placeholder="Percent" style="width:100px" oninput="doPc()"><span>% of</span><input type="number" id="pcn-base" placeholder="Number" style="width:100px" oninput="doPc()"><span>=</span><span id="pcn-result" style="font-size:18px;font-weight:700;color:#60a5fa">0</span></div>''';else if(m===1)c.innerHTML='''+'''<div style="display:flex;gap:8px;align-items:center;margin-top:12px;flex-wrap:wrap"><span>From</span><input type="number" id="pcc-from" placeholder="Old" style="width:100px" oninput="doPcChange()"><span>to</span><input type="number" id="pcc-to" placeholder="New" style="width:100px" oninput="doPcChange()"><span>=</span><span id="pcc-result" style="font-size:18px;font-weight:700;color:#60a5fa">0%</span></div>''';else c.innerHTML='''+'''<div style="display:flex;gap:8px;align-items:center;margin-top:12px;flex-wrap:wrap"><span>Bill:</span><input type="number" id="tip-bill" placeholder="Amount" style="width:100px" oninput="doTip()"><span>Tip:</span><input type="number" id="tip-pct" value="15" style="width:70px" oninput="doTip()"><span>%</span><span>=</span><span id="tip-result" style="font-size:18px;font-weight:700;color:#60a5fa">$0.00</span></div>'''}
window.doPc=()=>{var v=parseFloat(document.getElementById("pcn-val").value)||0,b=parseFloat(document.getElementById("pcn-base").value)||0;document.getElementById("pcn-result").textContent=(b*v/100).toFixed(2)}
window.doPcChange=()=>{var f=parseFloat(document.getElementById("pcc-from").value)||0,t=parseFloat(document.getElementById("pcc-to").value)||0;document.getElementById("pcc-result").textContent=f?((t-f)/f*100).toFixed(1)+"%":"0%"}
window.doTip=()=>{var b=parseFloat(document.getElementById("tip-bill").value)||0,p=parseFloat(document.getElementById("tip-pct").value)||0,t=b*p/100;document.getElementById("tip-result").textContent="$"+(b+t).toFixed(2)+" (tip $"+t.toFixed(2)+")"}
</script>
</body>
</html>'''

out = r'C:\Users\Administrator\Documents\Codex\2026-07-30\w\work\ai-tools\index.html'
with open(out, 'w', encoding='utf-8') as f:
    f.write(html)
print('Written:', out, os.path.getsize(out), 'bytes')
